### PR TITLE
ONIXDeviceDescriptor and static ReadRegister & WriteRegister

### PR DESCRIPTION
**Pull request by jonnew**
This idea need some work to deal with UI performance hits and sensical integration with I2CConfiguration.

### CODE REVIEW

**Comment by aacuevas** [comment]
Seems good! As you say, I2CConfiguration still needs some overhauls so it uses the static *Register methods, but I like the way this is going.

My only concern is, I would add again the checks I originally added to get the hub and clock info for a device. Those are slow (specially hub, since it's several register accesses) and asking for them again continuously, unless the device address changes, could end being an unnecessary performance hit.

**Comment by jonnew** [comment]
I think this is ready to merge whenever you have a chance to look at it @aacuevas.

**Comment by jonnew** [comment]
Re the performance issue above. I looked through the usage of `ONIDevice.FrameClockHz` and `ONIDevice.Hub` and they are all static (configuration or workflow build time). I suggest that we leave out the caching in favor of simplicity for now.

**Comment by jonnew** [comment]
Fixes #8

**Pull request merged**
